version: "3"
services:
  redis:
    image: redis
    ports:
      - "127.0.0.1:6379:6379" 
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
       - "127.0.0.1:5432:5432" 
  # sidekiq:
  #   build: .
  #   volumes:
  #     - .:/api_juior
  #   links:
  #     - db
  #     - redis
  #   command: bundle exec sidekiq
